### ISSUE TITLE
v4.1 - PC & Mobile - New Request - ensure if SRF set to annual allowance the allowance window opens and applies the allowance

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#131]
web service done. 
![traveller annual allowance](https://cloud.githubusercontent.com/assets/8541037/4990899/af0be9ca-69e1-11e4-9dc4-3157f9424347.png)

Once request saved the details will be included in the summary for this address and the number permitted will be reduced.
When quota reached the window still appears but has the ok button disabled and the request cannot be saved, refer below screen print
![traveller annual allowance quota](https://cloud.githubusercontent.com/assets/8541037/4990908/ca21e2e6-69e1-11e4-976d-a126a8db6a89.png)

**Comment by rmcallister** [comment]
keyword = cleanup and this window should open when submit or save&more selected

**Comment by rmcallister** [comment]
window not displayed when location address opens matching properties window e.g. 1 a'beckett close. 
Also there are 3 addresses which say none available but they still have available in client

![traveller allowance](https://cloud.githubusercontent.com/assets/8541037/5994591/5c1e298e-aace-11e4-8de4-d4d795a57f39.png)
![traveller allowance2](https://cloud.githubusercontent.com/assets/8541037/5994597/72d67898-aace-11e4-9c29-c804cc4c4ca3.png)
![traveller allowance3](https://cloud.githubusercontent.com/assets/8541037/5994598/76f496b2-aace-11e4-8922-94f047814084.png)

**Comment by hirpara-poonam** [comment]
requires ws to be change, will ask angel tomo morning to do that.

**Comment by rmcallister** [comment]
angle mentioned this afternoon that web service was returning data and she sent you a Skype message. Did you get this message? Is there something else that needs to happen after this?

**Comment by rmcallister** [comment]
number available displayed correctly now but once 1 allocated its not updating the available number nor displaying in history section. Angel updating web service

**Comment by rmcallister** [comment]
apply above fix for addresses not displaying availability correctly to mobile

**Comment by rmcallister** [comment]
all working now except displaying full history for address only displaying current period

**Comment by rmcallister** [comment]
full history working now however it seems to apply an allowance when count only used and shouldn't. Also when save&more used for annual allowance the 2nd request is not saved, loading indicator keeps spinning

**Comment by rmcallister** [comment]
working on pc and mobile
