### ISSUE TITLE
v4.1 - PC & Mobile - New Request - Customer Name - when existing name selected and the given name and/or surname is amended, upon save there should be a prompt like client which asks user to update original name or create a new name

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#153]
![traveller customer name changed](https://cloud.githubusercontent.com/assets/8541037/5241685/361f8594-7977-11e4-844a-3a72b8b23145.png)
if yes selected, then details should be changed for the existing name for all future selections and all existing requests.
If no selected, then create new merit name

**Comment by jamesMerit** [comment]
Save and more button worked when spoofing iphone 6, 6plus and nexus 10

**Comment by rmcallister** [comment]
submit button triggers the modify name window correctly however as soon as you click in the window or on yes or no buttons the windows disappears and nothing happens. Works now for save&more button but takes a very long time to save request and not sure it actually does save as the loading indicator keeps spinning. I'm using keyword = kit

**Comment by jamesMerit** [comment]
Pc or Mobile, it works on pc for me and when i spoof mobile it works and it works on my phone
