### ISSUE TITLE
v4.1.2 - PC & Mobile - Provide edit icon to enable action due date to be changed if workflow permits

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#157]
angel to create web service once complete the edit icon should be displayed in the following locations only where permitted of course. ![traveller change action due date - view request-actions](https://cloud.githubusercontent.com/assets/8541037/5273117/ee48868c-7ad7-11e4-9231-097bf70f107b.png)
![traveller change action due date - view action](https://cloud.githubusercontent.com/assets/8541037/5273120/f83b6bdc-7ad7-11e4-8273-0cd7d0383a59.png)

**Comment by jamesMerit** [comment]
http://traveller.merit.com.au/crm/4.1/index.php?page=view-action&id=1607625

**Comment by jamesMerit** [comment]
Applied Changes

**Comment by jamesMerit** [comment]
![work](https://cloud.githubusercontent.com/assets/8540510/6102261/2ab9556c-b087-11e4-8968-a4b20815c5a0.png)

**Comment by rmcallister** [comment]
working in pc but need to display current due date and time when edit icon selected currently displaying blank
Apply to mobile too

**Comment by rmcallister** [comment]
pc all done just need to include in mobile view action

**Comment by jamesMerit** [comment]
Applied.

**Comment by rmcallister** [comment]
works for view action in pc and mobile
apply to view request and complete action

**Comment by jamesMerit** [comment]
Applied to pc view request

**Comment by rmcallister** [comment]
needs to be for view request>>actions>>due date

**Comment by jamesMerit** [comment]
Applied to PC view req-> actions

**Comment by rmcallister** [comment]
all working but when you click on edit icon, the time defaults to am and should reflect the time for action due date

**Comment by rmcallister** [comment]
fixed
