### ISSUE TITLE
v4.1 PC Customer Address - new format

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#177]
1. Clear button should clear flat suffix and street suffix too
2. Reduce field size for flat suffix and street suffix
3. Include validation for suffix fields to permit letters only
4. Enable PO Box value to be entered into own field for outside address only and pass to house_suffix field
5. Reduce size of fields as per screen print and move property number to second row after postcode
6. Ensure address values placed in correct fields for view address - unit currently displayed in street number field
http://traveller.merit.com.au/crm/4.1/index.php?page=view-address&id=288862
7. Apply all changes for customer address to mobile
![traveller customer address](https://cloud.githubusercontent.com/assets/8541037/5479758/47d0da7a-8694-11e4-94a6-f5ba5821ae09.png)

**Comment by rmcallister** [comment]
1 & 3 working
unit number and street number field to validate numbers only

**Comment by rmcallister** [comment]
apply suffix fields, validation and rules to location address too

**Comment by jamesMerit** [comment]
Working in PC

**Comment by rmcallister** [comment]
pc complete apply to mobile

**Comment by rmcallister** [comment]
working in pc & mobile
