### ISSUE TITLE
v4.1 PC & Mobile - Customer Details - Name Change Window should only appear when existing name selected and modified not when new name added

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#178]
currently when I enter a new name in new request and then press save or save&more the name change window appears with blank data for original and the name details in new...however this window is not required as there is no existing name

**Comment by jamesMerit** [comment]
Should no longer occur

**Comment by rmcallister** [comment]
works for submit button in pc and mobile but not save&more

**Comment by jamesMerit** [comment]
Applied some changes and tested this morning - when a new name is added PC/Mobile it will not display the window, when existing name picked it will not display unless it is changed, when existing name picked and changed it will display.
