### ISSUE TITLE
v4.1 PC & Mobile - View Request - Notifications - when the email notifcation message uses ' its replaced with ?

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#184]
![traveller notification record](https://cloud.githubusercontent.com/assets/8541037/5624144/8e69e830-95b4-11e4-911e-575000b5e9e4.jpg)

**Comment by jamesMerit** [comment]
Debugged with Angel - Can't replicate issue without more information.

Which browser/email application did this occur in for starters.

**Comment by rmcallister** [comment]
jo to organise remote access with NG to show you what's happening

**Comment by jmartinmerit** [comment]
I have fixed this at NG.  I copied the original text to Notepad, which in effect clears out any formatting (thanks James), and then pasted it back in.  Apostrophe now displays correctly in View Request>>Notifications for Auto Notifications.
