### ISSUE TITLE
v4.1 PC - New Request - autotype for SRF fields moves letters to next field once match made

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#192]
I know we have discussed this previously and I'm sure someone advised this wasn't easy to fix so if that's still the case then we will have to move to v5

Rob has identified that when you are typing in autotype fields, that if the match is made, the rest of the letters are used in the next field.

Eg. W-A-T-E-R – the perfect match happens after W-A-T, and then E-R are used in the next field.  You can then see that you don’t have a match to those letters so remove them, and type again.  But again, once you have a match, the next letters are populated in the Function field.  This is OK for SRF that have 3 levels, but if you only have 2 levels, the letter(s) are saved in the field, and can’t be edited.  
 ![traveller autotype srf](https://cloud.githubusercontent.com/assets/8541037/5699264/53e682dc-9a77-11e4-9acf-2a709d4b7784.png)

It is ignored once the Request has been saved, but the user may not have confidence of that.

Jo spoke to Harry about it, and he seems to think it is a bug.

**Comment by jamesMerit** [comment]
Will attempt to clear next field on autocomplete.

**Comment by rmcallister** [comment]
fixed for function field but cannot clear text from request field without stopping the auto movement from service to request once matched
