### ISSUE TITLE
v4.1 PC - Search - when search conducted on request id and you dont select on results but press new request from menu, it takes ages for new request page to load and when it does there is a web service error

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#193]
![traveller search error](https://cloud.githubusercontent.com/assets/8541037/5699528/ec4f0b0a-9a7e-11e4-8aaa-bb964c63ab64.png)
![traveller search error_2](https://cloud.githubusercontent.com/assets/8541037/5699534/036ea138-9a7f-11e4-84ae-8ffd1f236f26.png)
The search should be stopped once results displayed and user should be able to navigate away from this page before clicking on one of the results
eg req id 621228

**Comment by rmcallister** [comment]
when I search for john smith, it takes a long time to retrieve results and then I get the first error message above but results are returned. When I click on item it has the 2nd web service error above in view name window

**Comment by jamesMerit** [comment]
John smith is a timeout error, req id 621228 worked for me

**Comment by rmcallister** [comment]
issue relates to external traveller use and distance from office - works when using internal traveller - no further action
