### ISSUE TITLE
v4.1 PC & Mobile - display audit details for view name

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#199]

**Comment by rmcallister** [comment]
web service completed

**Comment by rmcallister** [comment]
in view name include another menu item after addresses called "Audit'. This is to be dynamic and only display if data exists for that name.
Table to be similar to view request>>audit however only requires the following columns:
Date, Officer, Field, Operation, Before, After

**Comment by rmcallister** [comment]
angel updating web service to provide count

**Comment by hirpara-poonam** [comment]
Rachael please confirm the layout, its ready to publish.

**Comment by rmcallister** [comment]
layout display correct for pc and mobile just missing data so referred to angel

**Comment by rmcallister** [comment]
fixed but 2 issues remain:
1. audit menu missing from view name mobile only
2. web service - officer missing when from engine

**Comment by rmcallister** [comment]
all working except audit menu missing in mobile if data exists

**Comment by rmcallister** [comment]
fixed
