### ISSUE TITLE
v4.1 PC & Mobile - attachments are not sent with email notifications for NG

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#206]
client records the attachment path in notification record and the attachment is saved against request but no attachment received in email notification.
Traveller has no record of attachment being included with notification and no attachment received with email notification
paul investigating

**Comment by jamesMerit** [comment]
Jo said this was no longer an issue

**Comment by rmcallister** [comment]
fixed
