### ISSUE TITLE
v4.1 Mobile - Complete Action - when only one action udf for the action its not displaying when outcome selected. Works in PC

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#207]
req id 619194 and act id 1605490
should have action udf = test but none displayed in mobile
http://traveller.merit.com.au/crm/4.1/index.php?page=view-action&id=1605490&d=complete

**Comment by hirpara-poonam** [comment]
related to ws problem mentioned for #208

**Comment by rmcallister** [comment]
fixed
