### ISSUE TITLE
v4.1 PC & Mobile - Complete Action - no action udfs are displayed when outcome = not started yet but works correctly when you select other outcomes

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#208]
web service passes all action udfs, so there must be filtering occurring in php

**Comment by rmcallister** [comment]
req id 619821 & 619762 all action udfs should be displayed except those specific to an outcome

**Comment by hirpara-poonam** [comment]
ws ws_get_action_completed returns note_ind = " " and note_ind = "NORESPONSE" and to show udfs, note_ind should not be "NORESPONSE".
I think I need to talk to angel before finding the problem in code, as far as know ws does not provides correct details and if its correct then we need to remove the"NORESPONSE" validation to display udfs. (Not sure if i remove it then anything else will disturb?)

**Comment by rmcallister** [comment]
ok we can discuss with angel on Tuesday, thanks

**Comment by rmcallister** [comment]
works in pc now but needs to identify which action udfs are mandatory. once complete apply to mobile

**Comment by rmcallister** [comment]
working in pc and mobile but it validates mandatory udfs when trying to add a comment when outcome = not started yet or entering values in udfs. As its too complicated to remove validation only for this outcome, the action udfs will not display mandatory now

**Comment by rmcallister** [comment]
fixed
