### ISSUE TITLE
v4.1 PC & Mobile - Complete Action - include a new section called "Next Steps/Action" under complete button which displays once the outcome has been selected. This section will display the action or actions that will be triggered based on the outcome selected. Also needs to display what happens with request status once processed e.g. remains open or finalised or resubmit

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#212]

**Comment by rmcallister** [comment]
No details displayed when outcome selected eg req id 621509, refer to screen print for what should be displayed
![traveller next steps](https://cloud.githubusercontent.com/assets/8541037/5936477/20164e00-a739-11e4-9687-445760622e8c.png)
![traveller next steps client](https://cloud.githubusercontent.com/assets/8541037/5936488/38fe9666-a739-11e4-8b42-ffef1a0e7edb.png)

Change display as per screen print. Action name and action officer on same line and if multiple actions triggered then separate line for each action
![traveller next actions](https://cloud.githubusercontent.com/assets/8541037/5936394/5c24d1a6-a738-11e4-919f-ed2baeea37cf.png)

**Comment by rmcallister** [comment]
please rename Req status to Request status
angel said the web service is returning data as per client so she needs to debug with you to figure out why its not working in traveller. no data displayed the first time and then when you refresh complete action page and select outcome again it shows details from previous action but details still missing
http://traveller.merit.com.au/crm/4.1/index.php?page=view-action&id=1607513&d=complete 
http://traveller.merit.com.au/crm/4.1/index.php?page=view-action&id=1607461&d=complete
http://traveller.merit.com.au/crm/4.1/index.php?page=view-action&id=1606045&d=complete

**Comment by jamesMerit** [comment]
Checked with angel, data returned as per client - changed req status to Request status and fields now correctly reset, hide/ show

**Comment by rmcallister** [comment]
angel to update web service to ensure text for resubmit passed to request status and details for next action officer displayed correctly when set to adhoc officer, previous officer and officer in id no.

**Comment by rmcallister** [comment]
all working now except when action officer set to an officer within workflow - angel updating

**Comment by jamesMerit** [comment]
Applied changes, working in mobile

**Comment by rmcallister** [comment]
fixed
