### ISSUE TITLE
v4.1 PC & Mobile - View Request & View Action - request input time should not be 24 hour

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#214]
![traveller view request input time](https://cloud.githubusercontent.com/assets/8541037/5932089/5e825da2-a6fb-11e4-9d6d-3e433f514355.png)

**Comment by jamesMerit** [comment]
Fixed

**Comment by jamesMerit** [comment]
There's no time section on Date Input for mobile.

**Comment by rmcallister** [comment]
fixed
