### ISSUE TITLE
v4.1 PC - My Preferences - Success message always displays changed action and request default filters even if neither were changed

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#217]
when changing start up , how received, centre etc the success message also says action and request default filter changed but there was no change.
Also please put first letter of each word in success message with capital e.g Successfully Changed Request Default Filter

![traveller my preferences success message](https://cloud.githubusercontent.com/assets/8541037/6033097/85856754-ac65-11e4-8a91-d1824fde494b.png)

**Comment by rmcallister** [comment]
wording changed but still displaying success message for default filters even though they were changed

**Comment by jamesMerit** [comment]
Applied Fix

**Comment by rmcallister** [comment]
fixed
