### ISSUE TITLE
v4.1.2 Mobile & PC - Complete Action - once action completed you are returned to action intray for users default filter but it should go to the previous filter that was being used so they can continue to process actions without having to reselect the filter - pittwater

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#232]
ensure this fix does not affect the issues fixed with my preferences default filter being changed when action completed

**Comment by jamesMerit** [comment]
http://traveller.merit.com.au/crm/4.1.3/index.php?page=actions&filter=598438 - Fixed for PC, testing in mobile now

**Comment by jamesMerit** [comment]
Seems to be working for mobile, could be a bit glitchy, but the mobile code is not worth the huge amount of time to rework

**Comment by jamesMerit** [comment]
All working for me.

**Comment by rmcallister** [comment]
fixed
