### ISSUE TITLE
v4.1.4 - PC & Mobile - New Request - when entering customer name with title given and surname and there is a match for the given and surname but not for the title there is a blank window opened in pc and in mobile the screen freezes - marrickville

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#247]
e.g. mrs martin mcallister

**Comment by jmartinmerit** [comment]
Rachael, do you want Title column to display in the Matching Names?

**Comment by rmcallister** [comment]
yes please if its easy to add title column in matching names

**Comment by rmcallister** [comment]
search no longer includes title all titles appear however there will be column filters included in matching names window to enable filtering on title

**Comment by rmcallister** [comment]
search does not commence now until surname entered with either given name or title. Company search continues with that value. Blank window no longer appearing
